if(NOT DEFINED PTK_REQUIRED_AVIUTL2_VERSION OR "${PTK_REQUIRED_AVIUTL2_VERSION}" STREQUAL "")
  message(FATAL_ERROR "PTK_REQUIRED_AVIUTL2_VERSION is not defined")
endif()

if(NOT DEFINED PTK_REQUIRED_GCMZDROPS_VERSION_TAG OR "${PTK_REQUIRED_GCMZDROPS_VERSION_TAG}" STREQUAL "")
  message(FATAL_ERROR "PTK_REQUIRED_GCMZDROPS_VERSION_TAG is not defined")
endif()

function(ptk_set_required_aviutl2_version version)
  if(NOT version MATCHES "^([0-9]+)\\.([0-9]+)beta([0-9]+)$")
    message(FATAL_ERROR "Invalid AviUtl ExEdit2 version: ${version}")
  endif()

  set(_major "${CMAKE_MATCH_1}")
  set(_minor "${CMAKE_MATCH_2}")
  set(_beta "${CMAKE_MATCH_3}")

  math(EXPR _uint32 "${_major} * 1000000 + ${_minor} * 10000 + ${_beta} * 100")

  set(PTK_REQUIRED_AVIUTL2_VERSION_DISPLAY "${version}" PARENT_SCOPE)
  set(PTK_REQUIRED_AVIUTL2_VERSION_NAME "version${version}" PARENT_SCOPE)
  set(PTK_REQUIRED_AVIUTL2_VERSION_UINT32 "${_uint32}" PARENT_SCOPE)
endfunction()

function(ptk_set_required_ptk_version prefix version_tag)
  if(NOT version_tag MATCHES "^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(alpha|beta|rc)?([0-9]+)?$")
    message(FATAL_ERROR "Invalid ${prefix} version tag: ${version_tag}")
  endif()

  set(_major "${CMAKE_MATCH_1}")
  set(_minor "${CMAKE_MATCH_2}")
  set(_patch "${CMAKE_MATCH_3}")
  set(_stage_name "${CMAKE_MATCH_4}")
  set(_stage_number "${CMAKE_MATCH_5}")

  if(_major GREATER 127)
    message(FATAL_ERROR "Major version ${_major} exceeds limit 127")
  endif()
  if(_minor GREATER 255)
    message(FATAL_ERROR "Minor version ${_minor} exceeds limit 255")
  endif()
  if(_patch GREATER 255)
    message(FATAL_ERROR "Patch version ${_patch} exceeds limit 255")
  endif()

  if("${_stage_name}" STREQUAL "")
    set(_stage 511)
  elseif("${_stage_number}" STREQUAL "")
    message(FATAL_ERROR "Invalid ${prefix} version stage number: ${version_tag}")
  elseif("${_stage_name}" STREQUAL "alpha")
    if(_stage_number GREATER 169)
      message(FATAL_ERROR "Alpha version ${_stage_number} exceeds limit 169")
    endif()
    set(_stage "${_stage_number}")
  elseif("${_stage_name}" STREQUAL "beta")
    if(_stage_number GREATER 169)
      message(FATAL_ERROR "Beta version ${_stage_number} exceeds limit 169")
    endif()
    math(EXPR _stage "170 + ${_stage_number}")
  elseif("${_stage_name}" STREQUAL "rc")
    if(_stage_number GREATER 170)
      message(FATAL_ERROR "RC version ${_stage_number} exceeds limit 170")
    endif()
    math(EXPR _stage "340 + ${_stage_number}")
  else()
    message(FATAL_ERROR "Invalid ${prefix} version stage: ${version_tag}")
  endif()

  math(EXPR _uint32 "${_major} * 33554432 + ${_minor} * 131072 + ${_patch} * 512 + ${_stage}")

  set(${prefix}_VERSION_TAG "${version_tag}" PARENT_SCOPE)
  set(${prefix}_VERSION_UINT32 "${_uint32}" PARENT_SCOPE)
endfunction()

ptk_set_required_aviutl2_version("${PTK_REQUIRED_AVIUTL2_VERSION}")
ptk_set_required_ptk_version(PTK_REQUIRED_GCMZDROPS "${PTK_REQUIRED_GCMZDROPS_VERSION_TAG}")
